"""new

Revision ID: 04ceb52d2f5c
Revises: 50c3057bcbb8
Create Date: 2024-07-04 18:55:54.166609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ceb52d2f5c'
down_revision: Union[str, None] = '50c3057bcbb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'access')
    op.drop_column('lessons', 'access')
    op.drop_column('themes', 'access')
    op.alter_column('users', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('themes', sa.Column('access', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('lessons', sa.Column('access', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('access', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
