"""new

Revision ID: 50c3057bcbb8
Revises: a7d8cd6de89b
Create Date: 2024-07-04 18:23:57.388277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c3057bcbb8'
down_revision: Union[str, None] = 'a7d8cd6de89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('blocks', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('themes', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('themes', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('users', sa.Column('access', sa.Boolean(), nullable=True))
    op.drop_column('users', 'tin')
    op.drop_column('users', 'business')
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    op.drop_column('users', 'organization')
    op.drop_column('users', 'web_site')
    op.drop_column('users', 'post')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('post', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('web_site', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('organization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('business', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('tin', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'access')
    op.alter_column('themes', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('themes', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('blocks', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('blocks', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
