"""confirmation

Revision ID: 516679394703
Revises: d1e2cf610966
Create Date: 2024-07-07 22:48:12.343668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516679394703'
down_revision: Union[str, None] = 'd1e2cf610966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(), nullable=True))
    op.drop_column('users', 'confirmed_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'verified_email')
    # ### end Alembic commands ###
