"""Done

Revision ID: 547b5a6fe218
Revises: b609abe9f39e
Create Date: 2024-07-04 18:01:02.978677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547b5a6fe218'
down_revision: Union[str, None] = 'b609abe9f39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('access', sa.Boolean(), nullable=True))
    op.add_column('blocks', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('lessons', sa.Column('access', sa.Boolean(), nullable=True))
    op.add_column('lessons', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('themes', sa.Column('access', sa.Boolean(), nullable=True))
    op.add_column('themes', sa.Column('available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'available')
    op.drop_column('themes', 'access')
    op.drop_column('lessons', 'available')
    op.drop_column('lessons', 'access')
    op.drop_column('blocks', 'available')
    op.drop_column('blocks', 'access')
    # ### end Alembic commands ###
