"""Up

Revision ID: 6366f284227d
Revises: d2fea48c61cb
Create Date: 2024-06-30 19:30:33.867319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6366f284227d'
down_revision: Union[str, None] = 'd2fea48c61cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('lesson', sa.String(), nullable=False),
    sa.Column('theory_source', sa.String(), nullable=False),
    sa.Column('practice_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blocks', sa.Column('block_name', sa.String(), nullable=False))
    op.drop_column('blocks', 'practice_source')
    op.drop_column('blocks', 'lesson')
    op.drop_column('blocks', 'theory_source')
    op.drop_column('blocks', 'block')
    op.drop_column('blocks', 'theme')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('blocks', sa.Column('block', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('blocks', sa.Column('theory_source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('blocks', sa.Column('lesson', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('blocks', sa.Column('practice_source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('blocks', 'block_name')
    op.drop_table('themes')
    # ### end Alembic commands ###
