"""new

Revision ID: a7d8cd6de89b
Revises: 547b5a6fe218
Create Date: 2024-07-04 18:19:20.479577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d8cd6de89b'
down_revision: Union[str, None] = '547b5a6fe218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('blocks', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('themes', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('themes', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('themes', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('themes', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('blocks', 'available',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('blocks', 'access',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
