"""empty message

Revision ID: b609abe9f39e
Revises: fb231a818ee0
Create Date: 2024-07-01 22:25:11.958064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b609abe9f39e'
down_revision: Union[str, None] = 'fb231a818ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('lesson_name', sa.String(), nullable=False),
    sa.Column('theory_source', sa.String(), nullable=False),
    sa.Column('practice_source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('themes', sa.Column('theme_name', sa.String(), nullable=False))
    op.drop_column('themes', 'practice_source')
    op.drop_column('themes', 'theme')
    op.drop_column('themes', 'lesson')
    op.drop_column('themes', 'theory_source')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('theory_source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('themes', sa.Column('lesson', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('themes', sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('themes', sa.Column('practice_source', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('themes', 'theme_name')
    op.drop_table('lessons')
    # ### end Alembic commands ###
