"""confirmation

Revision ID: d1e2cf610966
Revises: 04ceb52d2f5c
Create Date: 2024-07-07 22:17:59.069420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e2cf610966'
down_revision: Union[str, None] = '04ceb52d2f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed_email', sa.Boolean(), nullable=True, insert_default=False, default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed_email')
    # ### end Alembic commands ###
